### ISSUE TITLE
Community Posts Issues

### ISSUE THREAD

**Issue by OasisOgre** [arichorn/uYouEnhanced#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.7
- Device model: iPad (9th Gen)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore 5.1
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.38.2-3.0.1](https://github.com/arichorn/uYouPlusExtra/releases/tag/v18.38.2-3.0.1)

### Describe the bug
1st Video: When I go to community tab on a channel, all the community post disappear permanently as I scroll down.

https://github.com/arichorn/uYouPlusExtra/assets/119268684/d1b95582-2ae4-4e5b-b2e6-31bb224d6fbe

--------

2nd Video: When I tap on a community post on the home tab, the post disappears permanently.

https://github.com/arichorn/uYouPlusExtra/assets/119268684/c84b3ca9-b3da-4750-9f33-1ce29becf3b0

### Steps to reproduce the issue

Just follow the steps of the video (works on all youtube light/dark themes)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I turned off no community posts option, so the bug is probably not related to that

**Comment by PoopieInMyIceCream** [comment]
@arichorn
