### ISSUE TITLE
Restore Previous Channel Page Option doesn't show Channel Page

### ISSUE THREAD

**Issue by OasisOgre** [arichorn/uYouEnhanced#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.7.2
- Device model: 9th Gen iPad
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.4.3-3.0.1

### Describe the bug

When I turn on "Restore the Previous Channel Page" option in UI Options and go to a channel, it doesnt restore the channel page. Instead, it breaks the channel along with playlists when I turn the option on.

(very wide black gap is a bug, also no channel page despite me turning on the option)
![IMG_0139](https://github.com/arichorn/uYouEnhanced/assets/119268684/c25c87dc-754c-44cc-8cec-c189a8c52aa8)
-
(on the top, transparent black rectangle is a bug)
![IMG_0140](https://github.com/arichorn/uYouEnhanced/assets/119268684/64aadab1-3670-4705-ba0b-478b7c7a5a74)

### Steps to reproduce the issue

1. Go to uYouEnhanced's UI Options and turn on "Restore the Previous Channel Page"
2. Go to a channel and see the bugs, along with the still missing channel page.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I also noticed the bug reports highly increased when this update was dropped, so I recommend you urgently focus on fixing those too

**Comment by JudeTheTechSavvyDude** [comment]
I have an brother that is an developer that can help you for sure, he does coding

**Comment by bhackel** [comment]
Is this issue resolved then? Also, I am interested in helping out with bug reports if needed, I am slowly figuring out how this tweak pack works.

**Comment by PoopieInMyIceCream** [comment]
@bhackel Well the option was removed via a commit below aricorn's reply. Apparently Youtube broke the channel tab option when they removed it

**Comment by OasisOgre** [comment]
yeah the dev said it's unfixable, closing this now (screw Youtube for making the dumbest change ever)

**Comment by OasisOgre** [comment]
dev said it's unfixable

**Comment by OasisOgre** [comment]
yeah the dev said it's unfixable, closing this now (screw Youtube for making the dumbest change ever)
